apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: orion-ns
  labels:
    service: orion-ledger-data
  name: orion-ledger-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
