// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseHeader struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{0}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

// GetDBStatus
type GetDBStatusResponseEnvelope struct {
	Response             *GetDBStatusResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte               `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDBStatusResponseEnvelope) Reset()         { *m = GetDBStatusResponseEnvelope{} }
func (m *GetDBStatusResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDBStatusResponseEnvelope) ProtoMessage()    {}
func (*GetDBStatusResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{1}
}

func (m *GetDBStatusResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBStatusResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDBStatusResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBStatusResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDBStatusResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBStatusResponseEnvelope.Merge(m, src)
}
func (m *GetDBStatusResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDBStatusResponseEnvelope.Size(m)
}
func (m *GetDBStatusResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBStatusResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBStatusResponseEnvelope proto.InternalMessageInfo

func (m *GetDBStatusResponseEnvelope) GetResponse() *GetDBStatusResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetDBStatusResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDBStatusResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Exist                bool            `protobuf:"varint,2,opt,name=exist,proto3" json:"exist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetDBStatusResponse) Reset()         { *m = GetDBStatusResponse{} }
func (m *GetDBStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetDBStatusResponse) ProtoMessage()    {}
func (*GetDBStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{2}
}

func (m *GetDBStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDBStatusResponse.Unmarshal(m, b)
}
func (m *GetDBStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDBStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetDBStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDBStatusResponse.Merge(m, src)
}
func (m *GetDBStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetDBStatusResponse.Size(m)
}
func (m *GetDBStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDBStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDBStatusResponse proto.InternalMessageInfo

func (m *GetDBStatusResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDBStatusResponse) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

// GetData
type GetDataResponseEnvelope struct {
	Response             *GetDataResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetDataResponseEnvelope) Reset()         { *m = GetDataResponseEnvelope{} }
func (m *GetDataResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataResponseEnvelope) ProtoMessage()    {}
func (*GetDataResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{3}
}

func (m *GetDataResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponseEnvelope.Merge(m, src)
}
func (m *GetDataResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataResponseEnvelope.Size(m)
}
func (m *GetDataResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponseEnvelope proto.InternalMessageInfo

func (m *GetDataResponseEnvelope) GetResponse() *GetDataResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetDataResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Value                []byte          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Metadata             *Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{4}
}

func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (m *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(m, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetDataResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// GetUser
type GetUserResponseEnvelope struct {
	Response             *GetUserResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte           `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetUserResponseEnvelope) Reset()         { *m = GetUserResponseEnvelope{} }
func (m *GetUserResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetUserResponseEnvelope) ProtoMessage()    {}
func (*GetUserResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{5}
}

func (m *GetUserResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponseEnvelope.Unmarshal(m, b)
}
func (m *GetUserResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetUserResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponseEnvelope.Merge(m, src)
}
func (m *GetUserResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetUserResponseEnvelope.Size(m)
}
func (m *GetUserResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponseEnvelope proto.InternalMessageInfo

func (m *GetUserResponseEnvelope) GetResponse() *GetUserResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetUserResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetUserResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	User                 *User           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Metadata             *Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{6}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// GetConfig
type GetConfigResponseEnvelope struct {
	Response             *GetConfigResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetConfigResponseEnvelope) Reset()         { *m = GetConfigResponseEnvelope{} }
func (m *GetConfigResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponseEnvelope) ProtoMessage()    {}
func (*GetConfigResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{7}
}

func (m *GetConfigResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponseEnvelope.Unmarshal(m, b)
}
func (m *GetConfigResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetConfigResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponseEnvelope.Merge(m, src)
}
func (m *GetConfigResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponseEnvelope.Size(m)
}
func (m *GetConfigResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponseEnvelope proto.InternalMessageInfo

func (m *GetConfigResponseEnvelope) GetResponse() *GetConfigResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetConfigResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetConfigResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Config               *ClusterConfig  `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Metadata             *Metadata       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{8}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetConfigResponse) GetConfig() *ClusterConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *GetConfigResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// GetNodeConfig
type GetNodeConfigResponseEnvelope struct {
	Response             *GetNodeConfigResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetNodeConfigResponseEnvelope) Reset()         { *m = GetNodeConfigResponseEnvelope{} }
func (m *GetNodeConfigResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetNodeConfigResponseEnvelope) ProtoMessage()    {}
func (*GetNodeConfigResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{9}
}

func (m *GetNodeConfigResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeConfigResponseEnvelope.Unmarshal(m, b)
}
func (m *GetNodeConfigResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeConfigResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetNodeConfigResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeConfigResponseEnvelope.Merge(m, src)
}
func (m *GetNodeConfigResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetNodeConfigResponseEnvelope.Size(m)
}
func (m *GetNodeConfigResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeConfigResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeConfigResponseEnvelope proto.InternalMessageInfo

func (m *GetNodeConfigResponseEnvelope) GetResponse() *GetNodeConfigResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetNodeConfigResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetNodeConfigResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	NodeConfig           *NodeConfig     `protobuf:"bytes,2,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetNodeConfigResponse) Reset()         { *m = GetNodeConfigResponse{} }
func (m *GetNodeConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeConfigResponse) ProtoMessage()    {}
func (*GetNodeConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{10}
}

func (m *GetNodeConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeConfigResponse.Unmarshal(m, b)
}
func (m *GetNodeConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeConfigResponse.Merge(m, src)
}
func (m *GetNodeConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeConfigResponse.Size(m)
}
func (m *GetNodeConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeConfigResponse proto.InternalMessageInfo

func (m *GetNodeConfigResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetNodeConfigResponse) GetNodeConfig() *NodeConfig {
	if m != nil {
		return m.NodeConfig
	}
	return nil
}

// GetBlock
type GetBlockResponseEnvelope struct {
	Response             *GetBlockResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte            `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetBlockResponseEnvelope) Reset()         { *m = GetBlockResponseEnvelope{} }
func (m *GetBlockResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetBlockResponseEnvelope) ProtoMessage()    {}
func (*GetBlockResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{11}
}

func (m *GetBlockResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockResponseEnvelope.Unmarshal(m, b)
}
func (m *GetBlockResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetBlockResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResponseEnvelope.Merge(m, src)
}
func (m *GetBlockResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetBlockResponseEnvelope.Size(m)
}
func (m *GetBlockResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResponseEnvelope proto.InternalMessageInfo

func (m *GetBlockResponseEnvelope) GetResponse() *GetBlockResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetBlockResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetBlockResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	BlockHeader          *BlockHeader    `protobuf:"bytes,2,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetBlockResponse) Reset()         { *m = GetBlockResponse{} }
func (m *GetBlockResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockResponse) ProtoMessage()    {}
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{12}
}

func (m *GetBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockResponse.Unmarshal(m, b)
}
func (m *GetBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockResponse.Merge(m, src)
}
func (m *GetBlockResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockResponse.Size(m)
}
func (m *GetBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockResponse proto.InternalMessageInfo

func (m *GetBlockResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetBlockResponse) GetBlockHeader() *BlockHeader {
	if m != nil {
		return m.BlockHeader
	}
	return nil
}

// GetLedgerPath
type GetLedgerPathResponseEnvelope struct {
	Response             *GetLedgerPathResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetLedgerPathResponseEnvelope) Reset()         { *m = GetLedgerPathResponseEnvelope{} }
func (m *GetLedgerPathResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetLedgerPathResponseEnvelope) ProtoMessage()    {}
func (*GetLedgerPathResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{13}
}

func (m *GetLedgerPathResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerPathResponseEnvelope.Unmarshal(m, b)
}
func (m *GetLedgerPathResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerPathResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetLedgerPathResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerPathResponseEnvelope.Merge(m, src)
}
func (m *GetLedgerPathResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetLedgerPathResponseEnvelope.Size(m)
}
func (m *GetLedgerPathResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerPathResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerPathResponseEnvelope proto.InternalMessageInfo

func (m *GetLedgerPathResponseEnvelope) GetResponse() *GetLedgerPathResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetLedgerPathResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetLedgerPathResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	BlockHeaders         []*BlockHeader  `protobuf:"bytes,2,rep,name=block_headers,json=blockHeaders,proto3" json:"block_headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetLedgerPathResponse) Reset()         { *m = GetLedgerPathResponse{} }
func (m *GetLedgerPathResponse) String() string { return proto.CompactTextString(m) }
func (*GetLedgerPathResponse) ProtoMessage()    {}
func (*GetLedgerPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{14}
}

func (m *GetLedgerPathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerPathResponse.Unmarshal(m, b)
}
func (m *GetLedgerPathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerPathResponse.Marshal(b, m, deterministic)
}
func (m *GetLedgerPathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerPathResponse.Merge(m, src)
}
func (m *GetLedgerPathResponse) XXX_Size() int {
	return xxx_messageInfo_GetLedgerPathResponse.Size(m)
}
func (m *GetLedgerPathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerPathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerPathResponse proto.InternalMessageInfo

func (m *GetLedgerPathResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetLedgerPathResponse) GetBlockHeaders() []*BlockHeader {
	if m != nil {
		return m.BlockHeaders
	}
	return nil
}

// GetTxProof
type GetTxProofResponseEnvelope struct {
	Response             *GetTxProofResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetTxProofResponseEnvelope) Reset()         { *m = GetTxProofResponseEnvelope{} }
func (m *GetTxProofResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxProofResponseEnvelope) ProtoMessage()    {}
func (*GetTxProofResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{15}
}

func (m *GetTxProofResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxProofResponseEnvelope.Unmarshal(m, b)
}
func (m *GetTxProofResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxProofResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxProofResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxProofResponseEnvelope.Merge(m, src)
}
func (m *GetTxProofResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxProofResponseEnvelope.Size(m)
}
func (m *GetTxProofResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxProofResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxProofResponseEnvelope proto.InternalMessageInfo

func (m *GetTxProofResponseEnvelope) GetResponse() *GetTxProofResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetTxProofResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxProofResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Hashes               [][]byte        `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTxProofResponse) Reset()         { *m = GetTxProofResponse{} }
func (m *GetTxProofResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxProofResponse) ProtoMessage()    {}
func (*GetTxProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{16}
}

func (m *GetTxProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxProofResponse.Unmarshal(m, b)
}
func (m *GetTxProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxProofResponse.Marshal(b, m, deterministic)
}
func (m *GetTxProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxProofResponse.Merge(m, src)
}
func (m *GetTxProofResponse) XXX_Size() int {
	return xxx_messageInfo_GetTxProofResponse.Size(m)
}
func (m *GetTxProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxProofResponse proto.InternalMessageInfo

func (m *GetTxProofResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetTxProofResponse) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

// GetDataProof
type GetDataProofResponseEnvelope struct {
	Response             *GetDataProofResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetDataProofResponseEnvelope) Reset()         { *m = GetDataProofResponseEnvelope{} }
func (m *GetDataProofResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataProofResponseEnvelope) ProtoMessage()    {}
func (*GetDataProofResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{17}
}

func (m *GetDataProofResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataProofResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataProofResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataProofResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataProofResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataProofResponseEnvelope.Merge(m, src)
}
func (m *GetDataProofResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataProofResponseEnvelope.Size(m)
}
func (m *GetDataProofResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataProofResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataProofResponseEnvelope proto.InternalMessageInfo

func (m *GetDataProofResponseEnvelope) GetResponse() *GetDataProofResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetDataProofResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataProofResponse struct {
	Header               *ResponseHeader       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Path                 []*MPTrieProofElement `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetDataProofResponse) Reset()         { *m = GetDataProofResponse{} }
func (m *GetDataProofResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataProofResponse) ProtoMessage()    {}
func (*GetDataProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{18}
}

func (m *GetDataProofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataProofResponse.Unmarshal(m, b)
}
func (m *GetDataProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataProofResponse.Marshal(b, m, deterministic)
}
func (m *GetDataProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataProofResponse.Merge(m, src)
}
func (m *GetDataProofResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataProofResponse.Size(m)
}
func (m *GetDataProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataProofResponse proto.InternalMessageInfo

func (m *GetDataProofResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataProofResponse) GetPath() []*MPTrieProofElement {
	if m != nil {
		return m.Path
	}
	return nil
}

type MPTrieProofElement struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MPTrieProofElement) Reset()         { *m = MPTrieProofElement{} }
func (m *MPTrieProofElement) String() string { return proto.CompactTextString(m) }
func (*MPTrieProofElement) ProtoMessage()    {}
func (*MPTrieProofElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{19}
}

func (m *MPTrieProofElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MPTrieProofElement.Unmarshal(m, b)
}
func (m *MPTrieProofElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MPTrieProofElement.Marshal(b, m, deterministic)
}
func (m *MPTrieProofElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MPTrieProofElement.Merge(m, src)
}
func (m *MPTrieProofElement) XXX_Size() int {
	return xxx_messageInfo_MPTrieProofElement.Size(m)
}
func (m *MPTrieProofElement) XXX_DiscardUnknown() {
	xxx_messageInfo_MPTrieProofElement.DiscardUnknown(m)
}

var xxx_messageInfo_MPTrieProofElement proto.InternalMessageInfo

func (m *MPTrieProofElement) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

// GetHistoricalData
type GetHistoricalDataResponseEnvelope struct {
	Response             *GetHistoricalDataResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetHistoricalDataResponseEnvelope) Reset()         { *m = GetHistoricalDataResponseEnvelope{} }
func (m *GetHistoricalDataResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetHistoricalDataResponseEnvelope) ProtoMessage()    {}
func (*GetHistoricalDataResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{20}
}

func (m *GetHistoricalDataResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoricalDataResponseEnvelope.Unmarshal(m, b)
}
func (m *GetHistoricalDataResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoricalDataResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetHistoricalDataResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoricalDataResponseEnvelope.Merge(m, src)
}
func (m *GetHistoricalDataResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetHistoricalDataResponseEnvelope.Size(m)
}
func (m *GetHistoricalDataResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoricalDataResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoricalDataResponseEnvelope proto.InternalMessageInfo

func (m *GetHistoricalDataResponseEnvelope) GetResponse() *GetHistoricalDataResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetHistoricalDataResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetHistoricalDataResponse struct {
	Header               *ResponseHeader      `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Values               []*ValueWithMetadata `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetHistoricalDataResponse) Reset()         { *m = GetHistoricalDataResponse{} }
func (m *GetHistoricalDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetHistoricalDataResponse) ProtoMessage()    {}
func (*GetHistoricalDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{21}
}

func (m *GetHistoricalDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoricalDataResponse.Unmarshal(m, b)
}
func (m *GetHistoricalDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoricalDataResponse.Marshal(b, m, deterministic)
}
func (m *GetHistoricalDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoricalDataResponse.Merge(m, src)
}
func (m *GetHistoricalDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetHistoricalDataResponse.Size(m)
}
func (m *GetHistoricalDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoricalDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoricalDataResponse proto.InternalMessageInfo

func (m *GetHistoricalDataResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetHistoricalDataResponse) GetValues() []*ValueWithMetadata {
	if m != nil {
		return m.Values
	}
	return nil
}

// GetDataReaders
type GetDataReadersResponseEnvelope struct {
	Response             *GetDataReadersResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetDataReadersResponseEnvelope) Reset()         { *m = GetDataReadersResponseEnvelope{} }
func (m *GetDataReadersResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataReadersResponseEnvelope) ProtoMessage()    {}
func (*GetDataReadersResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{22}
}

func (m *GetDataReadersResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadersResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataReadersResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadersResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataReadersResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadersResponseEnvelope.Merge(m, src)
}
func (m *GetDataReadersResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataReadersResponseEnvelope.Size(m)
}
func (m *GetDataReadersResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadersResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadersResponseEnvelope proto.InternalMessageInfo

func (m *GetDataReadersResponseEnvelope) GetResponse() *GetDataReadersResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetDataReadersResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataReadersResponse struct {
	Header               *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ReadBy               map[string]uint32 `protobuf:"bytes,2,rep,name=read_by,json=readBy,proto3" json:"read_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDataReadersResponse) Reset()         { *m = GetDataReadersResponse{} }
func (m *GetDataReadersResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataReadersResponse) ProtoMessage()    {}
func (*GetDataReadersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{23}
}

func (m *GetDataReadersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataReadersResponse.Unmarshal(m, b)
}
func (m *GetDataReadersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataReadersResponse.Marshal(b, m, deterministic)
}
func (m *GetDataReadersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataReadersResponse.Merge(m, src)
}
func (m *GetDataReadersResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataReadersResponse.Size(m)
}
func (m *GetDataReadersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataReadersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataReadersResponse proto.InternalMessageInfo

func (m *GetDataReadersResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataReadersResponse) GetReadBy() map[string]uint32 {
	if m != nil {
		return m.ReadBy
	}
	return nil
}

// GetDataWriters
type GetDataWritersResponseEnvelope struct {
	Response             *GetDataWritersResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetDataWritersResponseEnvelope) Reset()         { *m = GetDataWritersResponseEnvelope{} }
func (m *GetDataWritersResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataWritersResponseEnvelope) ProtoMessage()    {}
func (*GetDataWritersResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{24}
}

func (m *GetDataWritersResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWritersResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataWritersResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWritersResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataWritersResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWritersResponseEnvelope.Merge(m, src)
}
func (m *GetDataWritersResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataWritersResponseEnvelope.Size(m)
}
func (m *GetDataWritersResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWritersResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWritersResponseEnvelope proto.InternalMessageInfo

func (m *GetDataWritersResponseEnvelope) GetResponse() *GetDataWritersResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetDataWritersResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataWritersResponse struct {
	Header               *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	WrittenBy            map[string]uint32 `protobuf:"bytes,2,rep,name=written_by,json=writtenBy,proto3" json:"written_by,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDataWritersResponse) Reset()         { *m = GetDataWritersResponse{} }
func (m *GetDataWritersResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataWritersResponse) ProtoMessage()    {}
func (*GetDataWritersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{25}
}

func (m *GetDataWritersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataWritersResponse.Unmarshal(m, b)
}
func (m *GetDataWritersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataWritersResponse.Marshal(b, m, deterministic)
}
func (m *GetDataWritersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataWritersResponse.Merge(m, src)
}
func (m *GetDataWritersResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataWritersResponse.Size(m)
}
func (m *GetDataWritersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataWritersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataWritersResponse proto.InternalMessageInfo

func (m *GetDataWritersResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataWritersResponse) GetWrittenBy() map[string]uint32 {
	if m != nil {
		return m.WrittenBy
	}
	return nil
}

// GetDataProvenance
type GetDataProvenanceResponseEnvelope struct {
	Response             *GetDataProvenanceResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetDataProvenanceResponseEnvelope) Reset()         { *m = GetDataProvenanceResponseEnvelope{} }
func (m *GetDataProvenanceResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetDataProvenanceResponseEnvelope) ProtoMessage()    {}
func (*GetDataProvenanceResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{26}
}

func (m *GetDataProvenanceResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataProvenanceResponseEnvelope.Unmarshal(m, b)
}
func (m *GetDataProvenanceResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataProvenanceResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetDataProvenanceResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataProvenanceResponseEnvelope.Merge(m, src)
}
func (m *GetDataProvenanceResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetDataProvenanceResponseEnvelope.Size(m)
}
func (m *GetDataProvenanceResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataProvenanceResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataProvenanceResponseEnvelope proto.InternalMessageInfo

func (m *GetDataProvenanceResponseEnvelope) GetResponse() *GetDataProvenanceResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetDataProvenanceResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDataProvenanceResponse struct {
	Header               *ResponseHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	KVs                  []*KVWithMetadata `protobuf:"bytes,2,rep,name=KVs,proto3" json:"KVs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetDataProvenanceResponse) Reset()         { *m = GetDataProvenanceResponse{} }
func (m *GetDataProvenanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataProvenanceResponse) ProtoMessage()    {}
func (*GetDataProvenanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{27}
}

func (m *GetDataProvenanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataProvenanceResponse.Unmarshal(m, b)
}
func (m *GetDataProvenanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataProvenanceResponse.Marshal(b, m, deterministic)
}
func (m *GetDataProvenanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataProvenanceResponse.Merge(m, src)
}
func (m *GetDataProvenanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataProvenanceResponse.Size(m)
}
func (m *GetDataProvenanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataProvenanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataProvenanceResponse proto.InternalMessageInfo

func (m *GetDataProvenanceResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDataProvenanceResponse) GetKVs() []*KVWithMetadata {
	if m != nil {
		return m.KVs
	}
	return nil
}

// GetTxIDsSubmittedBy
type GetTxIDsSubmittedByResponseEnvelope struct {
	Response             *GetTxIDsSubmittedByResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                       `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetTxIDsSubmittedByResponseEnvelope) Reset()         { *m = GetTxIDsSubmittedByResponseEnvelope{} }
func (m *GetTxIDsSubmittedByResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxIDsSubmittedByResponseEnvelope) ProtoMessage()    {}
func (*GetTxIDsSubmittedByResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{28}
}

func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.Unmarshal(m, b)
}
func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.Merge(m, src)
}
func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.Size(m)
}
func (m *GetTxIDsSubmittedByResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIDsSubmittedByResponseEnvelope proto.InternalMessageInfo

func (m *GetTxIDsSubmittedByResponseEnvelope) GetResponse() *GetTxIDsSubmittedByResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetTxIDsSubmittedByResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxIDsSubmittedByResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	TxIDs                []string        `protobuf:"bytes,2,rep,name=txIDs,proto3" json:"txIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTxIDsSubmittedByResponse) Reset()         { *m = GetTxIDsSubmittedByResponse{} }
func (m *GetTxIDsSubmittedByResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxIDsSubmittedByResponse) ProtoMessage()    {}
func (*GetTxIDsSubmittedByResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{29}
}

func (m *GetTxIDsSubmittedByResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxIDsSubmittedByResponse.Unmarshal(m, b)
}
func (m *GetTxIDsSubmittedByResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxIDsSubmittedByResponse.Marshal(b, m, deterministic)
}
func (m *GetTxIDsSubmittedByResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxIDsSubmittedByResponse.Merge(m, src)
}
func (m *GetTxIDsSubmittedByResponse) XXX_Size() int {
	return xxx_messageInfo_GetTxIDsSubmittedByResponse.Size(m)
}
func (m *GetTxIDsSubmittedByResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxIDsSubmittedByResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxIDsSubmittedByResponse proto.InternalMessageInfo

func (m *GetTxIDsSubmittedByResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetTxIDsSubmittedByResponse) GetTxIDs() []string {
	if m != nil {
		return m.TxIDs
	}
	return nil
}

type TxReceiptResponseEnvelope struct {
	Response             *TxReceiptResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TxReceiptResponseEnvelope) Reset()         { *m = TxReceiptResponseEnvelope{} }
func (m *TxReceiptResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*TxReceiptResponseEnvelope) ProtoMessage()    {}
func (*TxReceiptResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{30}
}

func (m *TxReceiptResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxReceiptResponseEnvelope.Unmarshal(m, b)
}
func (m *TxReceiptResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxReceiptResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *TxReceiptResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxReceiptResponseEnvelope.Merge(m, src)
}
func (m *TxReceiptResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_TxReceiptResponseEnvelope.Size(m)
}
func (m *TxReceiptResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_TxReceiptResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_TxReceiptResponseEnvelope proto.InternalMessageInfo

func (m *TxReceiptResponseEnvelope) GetResponse() *TxReceiptResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *TxReceiptResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TxReceiptResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Receipt              *TxReceipt      `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TxReceiptResponse) Reset()         { *m = TxReceiptResponse{} }
func (m *TxReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*TxReceiptResponse) ProtoMessage()    {}
func (*TxReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{31}
}

func (m *TxReceiptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxReceiptResponse.Unmarshal(m, b)
}
func (m *TxReceiptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxReceiptResponse.Marshal(b, m, deterministic)
}
func (m *TxReceiptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxReceiptResponse.Merge(m, src)
}
func (m *TxReceiptResponse) XXX_Size() int {
	return xxx_messageInfo_TxReceiptResponse.Size(m)
}
func (m *TxReceiptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxReceiptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxReceiptResponse proto.InternalMessageInfo

func (m *TxReceiptResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *TxReceiptResponse) GetReceipt() *TxReceipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type GetTxResponseEnvelope struct {
	Response             *TxReceiptResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTxResponseEnvelope) Reset()         { *m = GetTxResponseEnvelope{} }
func (m *GetTxResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetTxResponseEnvelope) ProtoMessage()    {}
func (*GetTxResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{32}
}

func (m *GetTxResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxResponseEnvelope.Unmarshal(m, b)
}
func (m *GetTxResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetTxResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxResponseEnvelope.Merge(m, src)
}
func (m *GetTxResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetTxResponseEnvelope.Size(m)
}
func (m *GetTxResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxResponseEnvelope proto.InternalMessageInfo

func (m *GetTxResponseEnvelope) GetResponse() *TxReceiptResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetTxResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetTxResponse struct {
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Tx:
	//	*GetTxResponse_DataTx
	//	*GetTxResponse_ConfigTx
	//	*GetTxResponse_UserTx
	//	*GetTxResponse_DatabaseTx
	Tx                   isGetTxResponse_Tx `protobuf_oneof:"Tx"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetTxResponse) Reset()         { *m = GetTxResponse{} }
func (m *GetTxResponse) String() string { return proto.CompactTextString(m) }
func (*GetTxResponse) ProtoMessage()    {}
func (*GetTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{33}
}

func (m *GetTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxResponse.Unmarshal(m, b)
}
func (m *GetTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxResponse.Marshal(b, m, deterministic)
}
func (m *GetTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxResponse.Merge(m, src)
}
func (m *GetTxResponse) XXX_Size() int {
	return xxx_messageInfo_GetTxResponse.Size(m)
}
func (m *GetTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxResponse proto.InternalMessageInfo

func (m *GetTxResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type isGetTxResponse_Tx interface {
	isGetTxResponse_Tx()
}

type GetTxResponse_DataTx struct {
	DataTx *DataTxEnvelope `protobuf:"bytes,2,opt,name=data_tx,json=dataTx,proto3,oneof"`
}

type GetTxResponse_ConfigTx struct {
	ConfigTx *ConfigTxEnvelope `protobuf:"bytes,3,opt,name=config_tx,json=configTx,proto3,oneof"`
}

type GetTxResponse_UserTx struct {
	UserTx *UserAdministrationTxEnvelope `protobuf:"bytes,4,opt,name=user_tx,json=userTx,proto3,oneof"`
}

type GetTxResponse_DatabaseTx struct {
	DatabaseTx *DataTxEnvelope `protobuf:"bytes,5,opt,name=database_tx,json=databaseTx,proto3,oneof"`
}

func (*GetTxResponse_DataTx) isGetTxResponse_Tx() {}

func (*GetTxResponse_ConfigTx) isGetTxResponse_Tx() {}

func (*GetTxResponse_UserTx) isGetTxResponse_Tx() {}

func (*GetTxResponse_DatabaseTx) isGetTxResponse_Tx() {}

func (m *GetTxResponse) GetTx() isGetTxResponse_Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *GetTxResponse) GetDataTx() *DataTxEnvelope {
	if x, ok := m.GetTx().(*GetTxResponse_DataTx); ok {
		return x.DataTx
	}
	return nil
}

func (m *GetTxResponse) GetConfigTx() *ConfigTxEnvelope {
	if x, ok := m.GetTx().(*GetTxResponse_ConfigTx); ok {
		return x.ConfigTx
	}
	return nil
}

func (m *GetTxResponse) GetUserTx() *UserAdministrationTxEnvelope {
	if x, ok := m.GetTx().(*GetTxResponse_UserTx); ok {
		return x.UserTx
	}
	return nil
}

func (m *GetTxResponse) GetDatabaseTx() *DataTxEnvelope {
	if x, ok := m.GetTx().(*GetTxResponse_DatabaseTx); ok {
		return x.DatabaseTx
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetTxResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetTxResponse_DataTx)(nil),
		(*GetTxResponse_ConfigTx)(nil),
		(*GetTxResponse_UserTx)(nil),
		(*GetTxResponse_DatabaseTx)(nil),
	}
}

type GetLedgerHeightResponseEnvelope struct {
	Response             *GetLedgerHeightResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Signature            []byte                   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetLedgerHeightResponseEnvelope) Reset()         { *m = GetLedgerHeightResponseEnvelope{} }
func (m *GetLedgerHeightResponseEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetLedgerHeightResponseEnvelope) ProtoMessage()    {}
func (*GetLedgerHeightResponseEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{34}
}

func (m *GetLedgerHeightResponseEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerHeightResponseEnvelope.Unmarshal(m, b)
}
func (m *GetLedgerHeightResponseEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerHeightResponseEnvelope.Marshal(b, m, deterministic)
}
func (m *GetLedgerHeightResponseEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerHeightResponseEnvelope.Merge(m, src)
}
func (m *GetLedgerHeightResponseEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetLedgerHeightResponseEnvelope.Size(m)
}
func (m *GetLedgerHeightResponseEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerHeightResponseEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerHeightResponseEnvelope proto.InternalMessageInfo

func (m *GetLedgerHeightResponseEnvelope) GetResponse() *GetLedgerHeightResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetLedgerHeightResponseEnvelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetLedgerHeightResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	LedgerHeight         uint64          `protobuf:"varint,2,opt,name=ledger_height,json=ledgerHeight,proto3" json:"ledger_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetLedgerHeightResponse) Reset()         { *m = GetLedgerHeightResponse{} }
func (m *GetLedgerHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetLedgerHeightResponse) ProtoMessage()    {}
func (*GetLedgerHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{35}
}

func (m *GetLedgerHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLedgerHeightResponse.Unmarshal(m, b)
}
func (m *GetLedgerHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLedgerHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetLedgerHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLedgerHeightResponse.Merge(m, src)
}
func (m *GetLedgerHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetLedgerHeightResponse.Size(m)
}
func (m *GetLedgerHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLedgerHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLedgerHeightResponse proto.InternalMessageInfo

func (m *GetLedgerHeightResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetLedgerHeightResponse) GetLedgerHeight() uint64 {
	if m != nil {
		return m.LedgerHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*ResponseHeader)(nil), "types.ResponseHeader")
	proto.RegisterType((*GetDBStatusResponseEnvelope)(nil), "types.GetDBStatusResponseEnvelope")
	proto.RegisterType((*GetDBStatusResponse)(nil), "types.GetDBStatusResponse")
	proto.RegisterType((*GetDataResponseEnvelope)(nil), "types.GetDataResponseEnvelope")
	proto.RegisterType((*GetDataResponse)(nil), "types.GetDataResponse")
	proto.RegisterType((*GetUserResponseEnvelope)(nil), "types.GetUserResponseEnvelope")
	proto.RegisterType((*GetUserResponse)(nil), "types.GetUserResponse")
	proto.RegisterType((*GetConfigResponseEnvelope)(nil), "types.GetConfigResponseEnvelope")
	proto.RegisterType((*GetConfigResponse)(nil), "types.GetConfigResponse")
	proto.RegisterType((*GetNodeConfigResponseEnvelope)(nil), "types.GetNodeConfigResponseEnvelope")
	proto.RegisterType((*GetNodeConfigResponse)(nil), "types.GetNodeConfigResponse")
	proto.RegisterType((*GetBlockResponseEnvelope)(nil), "types.GetBlockResponseEnvelope")
	proto.RegisterType((*GetBlockResponse)(nil), "types.GetBlockResponse")
	proto.RegisterType((*GetLedgerPathResponseEnvelope)(nil), "types.GetLedgerPathResponseEnvelope")
	proto.RegisterType((*GetLedgerPathResponse)(nil), "types.GetLedgerPathResponse")
	proto.RegisterType((*GetTxProofResponseEnvelope)(nil), "types.GetTxProofResponseEnvelope")
	proto.RegisterType((*GetTxProofResponse)(nil), "types.GetTxProofResponse")
	proto.RegisterType((*GetDataProofResponseEnvelope)(nil), "types.GetDataProofResponseEnvelope")
	proto.RegisterType((*GetDataProofResponse)(nil), "types.GetDataProofResponse")
	proto.RegisterType((*MPTrieProofElement)(nil), "types.MPTrieProofElement")
	proto.RegisterType((*GetHistoricalDataResponseEnvelope)(nil), "types.GetHistoricalDataResponseEnvelope")
	proto.RegisterType((*GetHistoricalDataResponse)(nil), "types.GetHistoricalDataResponse")
	proto.RegisterType((*GetDataReadersResponseEnvelope)(nil), "types.GetDataReadersResponseEnvelope")
	proto.RegisterType((*GetDataReadersResponse)(nil), "types.GetDataReadersResponse")
	proto.RegisterMapType((map[string]uint32)(nil), "types.GetDataReadersResponse.ReadByEntry")
	proto.RegisterType((*GetDataWritersResponseEnvelope)(nil), "types.GetDataWritersResponseEnvelope")
	proto.RegisterType((*GetDataWritersResponse)(nil), "types.GetDataWritersResponse")
	proto.RegisterMapType((map[string]uint32)(nil), "types.GetDataWritersResponse.WrittenByEntry")
	proto.RegisterType((*GetDataProvenanceResponseEnvelope)(nil), "types.GetDataProvenanceResponseEnvelope")
	proto.RegisterType((*GetDataProvenanceResponse)(nil), "types.GetDataProvenanceResponse")
	proto.RegisterType((*GetTxIDsSubmittedByResponseEnvelope)(nil), "types.GetTxIDsSubmittedByResponseEnvelope")
	proto.RegisterType((*GetTxIDsSubmittedByResponse)(nil), "types.GetTxIDsSubmittedByResponse")
	proto.RegisterType((*TxReceiptResponseEnvelope)(nil), "types.TxReceiptResponseEnvelope")
	proto.RegisterType((*TxReceiptResponse)(nil), "types.TxReceiptResponse")
	proto.RegisterType((*GetTxResponseEnvelope)(nil), "types.GetTxResponseEnvelope")
	proto.RegisterType((*GetTxResponse)(nil), "types.GetTxResponse")
	proto.RegisterType((*GetLedgerHeightResponseEnvelope)(nil), "types.GetLedgerHeightResponseEnvelope")
	proto.RegisterType((*GetLedgerHeightResponse)(nil), "types.GetLedgerHeightResponse")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_0fbc901015fa5021) }

var fileDescriptor_0fbc901015fa5021 = []byte{
	// 1130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x98, 0x4f, 0x53, 0xdb, 0x46,
	0x18, 0xc6, 0x6b, 0xfe, 0x18, 0x78, 0x0d, 0x04, 0x14, 0x02, 0x8e, 0x21, 0x09, 0x15, 0x87, 0x26,
	0x2d, 0x98, 0x96, 0x34, 0x09, 0xc9, 0x64, 0x32, 0x53, 0x27, 0x8c, 0x61, 0x28, 0x1d, 0x46, 0x71,
	0x61, 0x26, 0x3d, 0x78, 0xd6, 0xd2, 0xc6, 0xd2, 0x60, 0x4b, 0xee, 0xee, 0x1a, 0xec, 0xb6, 0x33,
	0x39, 0xf4, 0xde, 0x6f, 0xd0, 0x7b, 0x3f, 0x49, 0x3f, 0x40, 0x3f, 0x51, 0x67, 0x57, 0x2b, 0x4b,
	0xf2, 0x0a, 0x46, 0xcb, 0x21, 0x37, 0xaf, 0xf4, 0x3e, 0x8f, 0xf6, 0xf7, 0x48, 0xab, 0x7d, 0x65,
	0x58, 0x24, 0x98, 0xf6, 0x02, 0x9f, 0xe2, 0x6a, 0x8f, 0x04, 0x2c, 0x30, 0xa6, 0xd9, 0xb0, 0x87,
	0x69, 0xe5, 0xae, 0x1d, 0xf8, 0x1f, 0xbd, 0x76, 0x9f, 0x20, 0xe6, 0x05, 0x7e, 0x78, 0xae, 0xb2,
	0xde, 0xea, 0x04, 0xf6, 0x45, 0x13, 0xf9, 0x4e, 0x93, 0x11, 0xe4, 0x53, 0x64, 0xc7, 0x27, 0xcd,
	0x27, 0xb0, 0x68, 0x49, 0xab, 0x43, 0x8c, 0x1c, 0x4c, 0x8c, 0x35, 0x98, 0xf1, 0x03, 0x07, 0x37,
	0x3d, 0xa7, 0x5c, 0xd8, 0x2c, 0x3c, 0x9e, 0xb3, 0x8a, 0x7c, 0x78, 0xe4, 0x98, 0x14, 0xd6, 0xeb,
	0x98, 0xbd, 0xab, 0xbd, 0x67, 0x88, 0xf5, 0x69, 0xa4, 0x3a, 0xf0, 0x2f, 0x71, 0x27, 0xe8, 0x61,
	0xe3, 0x39, 0xcc, 0x46, 0x93, 0x12, 0xc2, 0xd2, 0x5e, 0xa5, 0x2a, 0x66, 0x55, 0xcd, 0x50, 0x59,
	0xa3, 0x5a, 0x63, 0x03, 0xe6, 0xa8, 0xd7, 0xf6, 0x11, 0xeb, 0x13, 0x5c, 0x9e, 0xd8, 0x2c, 0x3c,
	0x9e, 0xb7, 0xe2, 0x03, 0xe6, 0x07, 0xb8, 0x9b, 0x21, 0x37, 0x76, 0xa0, 0xe8, 0x8a, 0xe9, 0xca,
	0x4b, 0xdd, 0x93, 0x97, 0x4a, 0xb3, 0x58, 0xb2, 0xc8, 0x58, 0x81, 0x69, 0x3c, 0xf0, 0x28, 0x13,
	0xfe, 0xb3, 0x56, 0x38, 0x30, 0x2f, 0x60, 0x8d, 0x7b, 0x23, 0x86, 0x14, 0x98, 0x3d, 0x05, 0x66,
	0x35, 0x01, 0x93, 0x50, 0xe4, 0x06, 0xf9, 0xb3, 0x00, 0x77, 0xc6, 0xb4, 0xb7, 0xa0, 0xb8, 0x44,
	0x9d, 0x7e, 0x64, 0x1e, 0x0e, 0x8c, 0x6f, 0x60, 0xb6, 0x8b, 0x19, 0x72, 0x10, 0x43, 0xe5, 0x49,
	0x61, 0x73, 0x47, 0xda, 0x9c, 0xc8, 0xc3, 0xd6, 0xa8, 0x40, 0x22, 0xff, 0x4c, 0x31, 0xd1, 0x43,
	0x4e, 0x2a, 0x72, 0x23, 0xff, 0x15, 0x22, 0x27, 0xb5, 0xba, 0xc8, 0x8f, 0x60, 0xaa, 0x4f, 0x31,
	0x11, 0xde, 0xa5, 0xbd, 0x92, 0x2c, 0x16, 0x8e, 0xe2, 0x84, 0x1e, 0x7d, 0x00, 0xf7, 0xeb, 0x98,
	0xbd, 0x15, 0x6b, 0x44, 0xe1, 0xff, 0x5e, 0xe1, 0x2f, 0xc7, 0xfc, 0x69, 0x4d, 0xee, 0x04, 0xfe,
	0x2e, 0xc0, 0xb2, 0xa2, 0xd6, 0xcd, 0x60, 0x1b, 0x8a, 0xe1, 0xb2, 0x96, 0x29, 0xac, 0xc8, 0xf2,
	0xb7, 0x9d, 0x3e, 0x65, 0x98, 0x48, 0x73, 0x59, 0xa3, 0x17, 0xc8, 0x15, 0x3c, 0xa8, 0x63, 0xf6,
	0x53, 0xe0, 0xe0, 0x6b, 0x42, 0xd9, 0x57, 0x42, 0xd9, 0x88, 0x43, 0x51, 0x75, 0xb9, 0x83, 0xf9,
	0x0d, 0xee, 0x65, 0x1a, 0xe8, 0x66, 0xb3, 0x07, 0x25, 0xf1, 0xb2, 0x4a, 0x05, 0xb4, 0x2c, 0x35,
	0x09, 0x7b, 0xf0, 0x47, 0xbf, 0xcd, 0x2e, 0x94, 0xeb, 0x98, 0xd5, 0xf8, 0x4b, 0x51, 0xe1, 0x7d,
	0xaa, 0xf0, 0xae, 0xc5, 0xbc, 0x29, 0x49, 0x6e, 0xd4, 0x01, 0x2c, 0x8d, 0x6b, 0x75, 0x29, 0x9f,
	0xc1, 0x7c, 0xf8, 0x0e, 0x97, 0xa2, 0x10, 0xd3, 0x90, 0x22, 0x61, 0x2d, 0x15, 0xa5, 0x56, 0x3c,
	0x90, 0x77, 0xf7, 0x47, 0xec, 0xb4, 0x31, 0x39, 0x45, 0xcc, 0xd5, 0xbb, 0xbb, 0xaa, 0x2e, 0x37,
	0xf2, 0x27, 0x71, 0x77, 0x55, 0x03, 0x5d, 0xee, 0x17, 0xb0, 0x90, 0xe4, 0xa6, 0xe5, 0x89, 0xcd,
	0xc9, 0x6b, 0xc0, 0xe7, 0x13, 0xe0, 0xd4, 0xfc, 0x15, 0x2a, 0x75, 0xcc, 0x1a, 0x83, 0x53, 0x12,
	0x04, 0x1f, 0x15, 0xec, 0x67, 0x0a, 0xf6, 0xfd, 0x18, 0x7b, 0x4c, 0x94, 0x9b, 0xf9, 0x17, 0x30,
	0x54, 0xb5, 0x2e, 0xf0, 0x2a, 0x14, 0x5d, 0x44, 0x5d, 0x1c, 0x92, 0xce, 0x5b, 0x72, 0x64, 0xf6,
	0x61, 0x43, 0xee, 0x1d, 0xd9, 0x44, 0x2f, 0x14, 0xa2, 0xf5, 0xf4, 0x76, 0x75, 0x3b, 0x26, 0x06,
	0x2b, 0x59, 0x7a, 0x5d, 0xaa, 0x1d, 0x98, 0xea, 0x21, 0xe6, 0xca, 0xbb, 0x17, 0x65, 0x7d, 0x72,
	0xda, 0x20, 0x1e, 0x16, 0xc6, 0x07, 0x1d, 0xdc, 0xc5, 0x3e, 0xb3, 0x44, 0x99, 0xb9, 0x0d, 0x86,
	0x7a, 0x2e, 0x11, 0x4d, 0x21, 0x15, 0xcd, 0x27, 0xf8, 0xb2, 0x8e, 0xd9, 0xa1, 0x47, 0x59, 0x40,
	0x3c, 0x1b, 0x75, 0x32, 0xb7, 0xf3, 0xd7, 0x4a, 0x3e, 0x9b, 0x71, 0x3e, 0xd9, 0xda, 0xdc, 0x21,
	0xfd, 0x21, 0x36, 0x95, 0x6c, 0x13, 0xdd, 0xa4, 0xbe, 0x85, 0xa2, 0xd8, 0xd4, 0xa3, 0x27, 0x3d,
	0xda, 0x81, 0xce, 0xf8, 0xc1, 0x73, 0x8f, 0xb9, 0xa3, 0x77, 0xb8, 0xac, 0x33, 0x87, 0xf0, 0x70,
	0xd4, 0x55, 0x88, 0x67, 0x5f, 0x61, 0x7f, 0xa9, 0xb0, 0x3f, 0x18, 0x6f, 0x65, 0x52, 0xc2, 0xdc,
	0xe0, 0xff, 0x16, 0x60, 0x35, 0xdb, 0x42, 0x17, 0xbb, 0x06, 0x33, 0x04, 0x23, 0xa7, 0xd9, 0x1a,
	0x4a, 0xee, 0x27, 0x37, 0xce, 0xb0, 0xca, 0xc7, 0xb5, 0xe1, 0x81, 0xcf, 0xc8, 0xd0, 0x2a, 0x12,
	0x31, 0xa8, 0xbc, 0x84, 0x52, 0xe2, 0xb0, 0xb1, 0x04, 0x93, 0x17, 0x78, 0x28, 0x3b, 0x58, 0xfe,
	0x33, 0xdd, 0x3d, 0x2d, 0xc8, 0xee, 0xe9, 0xd5, 0xc4, 0x7e, 0x21, 0x91, 0xe1, 0x39, 0xf1, 0xd8,
	0xad, 0x32, 0x1c, 0x13, 0xe6, 0xce, 0xf0, 0xbf, 0x38, 0xc3, 0x31, 0x0b, 0xdd, 0x0c, 0x8f, 0x01,
	0xae, 0x88, 0xc7, 0x18, 0xf6, 0xe3, 0x18, 0xb7, 0x6f, 0x9c, 0x64, 0xf5, 0x3c, 0xac, 0x8f, 0x92,
	0x9c, 0xbb, 0x8a, 0xc6, 0x95, 0xd7, 0xb0, 0x98, 0x3e, 0xa9, 0x95, 0x67, 0xb8, 0x24, 0xe5, 0x6b,
	0xe3, 0x12, 0xfb, 0xc8, 0xb7, 0xb1, 0xde, 0x92, 0xcc, 0xd6, 0xe6, 0x4e, 0x95, 0x8a, 0x25, 0x99,
	0x6d, 0xa2, 0x9b, 0xeb, 0x57, 0x30, 0x79, 0x7c, 0x16, 0xad, 0xc7, 0xa8, 0xf6, 0xf8, 0x2c, 0xb5,
	0x18, 0x79, 0x05, 0x6f, 0xf0, 0xb7, 0xc4, 0x0e, 0x70, 0xf4, 0x8e, 0xbe, 0xef, 0xb7, 0xba, 0x3c,
	0x3e, 0xa7, 0x36, 0x54, 0xc0, 0xdf, 0x28, 0xe0, 0x66, 0x72, 0xf7, 0xc9, 0x56, 0xe7, 0x46, 0x6f,
	0x89, 0x8f, 0xb4, 0xeb, 0x6c, 0x6e, 0xf1, 0xc5, 0xc1, 0xb8, 0x95, 0xc0, 0x9f, 0xb3, 0xc2, 0x01,
	0x6f, 0xa3, 0x1b, 0x03, 0x0b, 0xdb, 0xd8, 0xeb, 0x31, 0x8d, 0x36, 0x5a, 0xd1, 0xe4, 0x86, 0xf2,
	0x61, 0x59, 0x11, 0xeb, 0xa2, 0x7c, 0xcd, 0xdf, 0x31, 0xc2, 0x41, 0xb6, 0x4f, 0x4b, 0xca, 0xb4,
	0xa2, 0x02, 0xf3, 0x42, 0xf4, 0x2f, 0xfc, 0xc4, 0x67, 0x80, 0xfb, 0x67, 0x02, 0x16, 0x52, 0x57,
	0xd3, 0xdf, 0x34, 0x66, 0xf8, 0x53, 0xd8, 0x64, 0x03, 0x49, 0x16, 0xd5, 0xf3, 0x05, 0xd0, 0x18,
	0x44, 0x93, 0x3f, 0xfc, 0xc2, 0x2a, 0x3a, 0xe2, 0x88, 0xf1, 0x1c, 0xe6, 0xc2, 0x86, 0x99, 0x6b,
	0x26, 0x53, 0x6d, 0x6e, 0xd8, 0x23, 0xa7, 0x54, 0xb3, 0xb6, 0x3c, 0x66, 0xbc, 0x81, 0x19, 0xfe,
	0xd1, 0xc5, 0x55, 0x53, 0x42, 0xb5, 0x95, 0xf8, 0x20, 0xfb, 0xc1, 0xe9, 0x7a, 0xbe, 0x47, 0x59,
	0xf8, 0xdf, 0x43, 0xfa, 0xba, 0x5c, 0xd5, 0x18, 0x18, 0xfb, 0x50, 0xe2, 0x33, 0x68, 0x21, 0x8a,
	0xb9, 0xc7, 0xf4, 0xcd, 0xb3, 0x85, 0xa8, 0xb6, 0x31, 0xa8, 0x4d, 0xc1, 0x44, 0x63, 0x60, 0xfe,
	0x0e, 0x8f, 0x46, 0x7d, 0xe5, 0x21, 0xf6, 0xda, 0xae, 0xfa, 0xf8, 0xbd, 0x52, 0xee, 0xd0, 0xc3,
	0xf1, 0x96, 0x36, 0xad, 0xcc, 0x7d, 0x9f, 0xba, 0xe2, 0xd3, 0x39, 0xcb, 0x42, 0xf7, 0x86, 0x6d,
	0xc1, 0x42, 0x47, 0xd8, 0x34, 0x5d, 0xe1, 0x23, 0xae, 0x35, 0x65, 0xcd, 0x77, 0x12, 0xde, 0xb5,
	0xef, 0x3e, 0xec, 0xb6, 0x3d, 0xe6, 0xf6, 0x5b, 0x55, 0x3b, 0xe8, 0xee, 0x1e, 0xd5, 0x4e, 0x76,
	0x44, 0xbb, 0x6b, 0xbb, 0xc8, 0xf3, 0x77, 0x5b, 0xb6, 0xd3, 0xda, 0xa1, 0x98, 0x5c, 0x62, 0xb2,
	0xdb, 0xbb, 0x68, 0xef, 0x8a, 0xcb, 0xb5, 0x8a, 0xe2, 0x2f, 0x9d, 0xa7, 0xff, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x20, 0xdf, 0x7b, 0xe5, 0x1d, 0x12, 0x00, 0x00,
}
